### ISSUE TITLE
Thanks! Great for investigating!

### ISSUE THREAD

**Issue by porg** [martinpitt/fatrace#12]
👍 Thanks for this cool software! 

## Super practical
- Being a macOS Unix/Terminal user for 20 years now, and now working with Linux too, it's the closest to macOS `fs_usage` I found.
- With this tool you very quickly find out **which process so far unknown to you** is causing **what file activity so far unknown to you** in no time.
- All the other Linux tools regarding "file system monitoring" presented on various blogs, forums, etc were not useful for my purposes because they either let you monitor a particular process or a particular directory/file or are disk centric. But none of them let you "investigate the unknown" in a quick and real time manner.
- Thanks!

I recommended your software on [StackExchange](https://superuser.com/questions/370070/linux-equivalent-to-mac-os-xs-fs-usage/1731935#1731935) and in some other places.

**Comment by porg** [comment]
After using it intensively the last 1-2 days I now compiled various proposals:
- #13
- #14 
- #16 
- #15
- #17 
- #18 

And reported these bugs
- #19 
- #20 
- #21 

Hope this helps!

**Comment by martinpitt** [comment]
Cheers, glad to hear! Thanks for the detailed issues, I'll respond there one by one.

**Comment by porg** [comment]
What's the proper Linux way to position that custom built until the repro receives the updates?
- In terms of location for binary plus man/helper files and $PATH or alias config?
  - So that I can call it with `fatrace` both as root and normal users and it overrules the normal location.
  - So `which fatrace`points to the custom build.
  - Or alternatively being available as `fatrace-nightly` to all users.

**Comment by martinpitt** [comment]
I recommend putting self-built binaries into /usr/local/bin/, that will have the properties you desire. That won't affect the manpage of course (but that doesn't change for bug fixes anyway). fatrace has no helper binaries.
