### ISSUE TITLE
Event type letter(s): Please make this a padded fixed-width format

### ISSUE THREAD

**Issue by porg** [martinpitt/fatrace#17]
- As the output for the file event is either 1 or 2 characters wide, please add a space after the 1 letter types, so that they all have the same width (in a monospace Terminal).
- If the Process name and filepath are the same, but the event type is different (1 or 2 letter event) the filepaths then all remain visually aligned. Much easier to comprehend.

- If you want to take visual alignment to the next level for output in general then consider proposal:
#15

**Comment by martinpitt** [comment]
It can also be 3 letters, "CWO" or "RCO" are quite common. It's even conceivable that a process opens a temp file and does all four at the same time (although less likely). So for now I'll use 3 columns. Thanks for the suggestion!
