### ISSUE TITLE
open_by_handle_at: Value too large for defined data type -- On 32-bit system when files >2GB get accessed

### ISSUE THREAD

**Issue by porg** [martinpitt/fatrace#19]
## Environment
- Open Media Vault 6 (based on Debian 11)
	- On an Odroid Home Cloud 2 (SBC with 32-bit ARM CPU + SD card + SATA HDD)
	- Using https://www.armbian.com/odroid-xu4/
	- Armbian 22.05.3 Bullseye with Linux 5.4.199-odroidxu4
- fatrace 0.16.2-2 (installed via apt)

## Reproduction
1. Logged in to my NAS via SSH as root and running `fatrace`
2. Accessing the NAS with a service (e.g. Samba or Plex)
3. ✅ `fatrace` shows nice output all the time.
4. ❌ But as soon as my activity causes access to a file larger than 2 GB I get this output:
  - `fatrace: open_by_handle_at: Value too large for defined data type`
  - Expected: I see the filepath and the file event type as for other files.

**Comment by porg** [comment]
One more note: Before reporting the bug I googled for the error message and found [this bug report](https://raspberrypi.stackexchange.com/questions/82261/value-too-large-for-defined-data-type-error-on-files-larger-than-2gb-only-in-r) in a totally unrelated project, but from there learned that this had to do with 32bit systems and filesystem calls differing when accessing files below 2GB and above 2GB. And then tested and confirmed this to be the case here for fatrace too.

**Comment by martinpitt** [comment]
The source already defines `_LARGEFILE64_SOURCE`, which ought to use the 64 bit versions. It also opens fanotify with `O_LARGEFILE`.  But I suppose that works already, as you get that error message so late. Indeed the open_by_handle_at() does not specify the flag, but it's allowed. I added this, can you please test current master?

**Comment by porg** [comment]
I have installed fatrace via `apt install fatrace` on an OpenMediaVault 6 NAS.

How do I do this there? never done this on Linux.
- Do you mean git cloning it to my user directory and then compiling it?
- Will this custom compiled version be stronger in the $PATH priority?
- - Or must `apt uninstall fatrace` first?

**Comment by martinpitt** [comment]
I built an ARM binary on bullseye for you, from current master: [fatrace.arm.bullseye.zip](https://github.com/martinpitt/fatrace/files/9129766/fatrace.arm.bullseye.zip). I zipped it so that I can attach it to github. Unzip it, and run `sudo ./fatrace.arm.bullseye`.

If that does not work, you can build yourself like this: First, make sure you have the C compiler and `make` installed:

    sudo apt install build-essential make

Then build it:
```
git clone https://github.com/martinpitt/fatrace/
cd fatrace
make
```

Now you can run `sudo ./fatrace ...` to run the locally built version, instead of the one in `$PATH` (which is /usr/bin/fatrace). Does that work for you?

**Comment by porg** [comment]
Success:
- Built it that way and fatrace now correctly shows also filepaths for files >2GB.
- Cool. Will this be included in the next official release, and will work automatically correctly on platforms like mine? Or must some configuration be done?

**Comment by martinpitt** [comment]
Thanks! I'll do a new release soon and upload it to Debian/Ubuntu/Fedora. But it won't go into bullseye, just into the next release (bookworm).
