### ISSUE TITLE
Doesn't work on Btrfs: Failed to add watch Invalid cross-device link

### ISSUE THREAD

**Issue by Mart-Bogdan** [martinpitt/fatrace#24]
When I try to run it on Btrfs that have sub-volumes,  I'm getting following message:

```
fatrace: Failed to add watch for /: Invalid cross-device link
```

fatrace-0.17.0

Kernel: 5.15.78-1-MANJARO

**Comment by martinpitt** [comment]
This is a known limitation of fanotify in the Linux kernel, see issue #3 for discussion and a workaround. Closing as duplicate.
