### ISSUE TITLE
Missing installation instructions for the MacOS

### ISSUE THREAD

**Issue by johnbizokk** [martinpitt/fatrace#28]
Hello! On the latest macOS - Ventura, I am receiving the following error after the make command invocation:
```
sh-3.2# make
/usr/local/Cellar/gcc/13.1.0/bin/gcc-13 -O2 -g -Wall -Wextra -Werror   -c -o fatrace.o fatrace.c
fatrace.c:32:10: fatal error: mntent.h: No such file or directory
   32 | #include <mntent.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [fatrace.o] Error 1
```
Are there any macOS-specific instructions for building the project from the source code?

**Comment by martinpitt** [comment]
There aren't instructions because the whole fanotify() API is strictly Linux only. You'll need a different tool on MacOS to trace file events system-wide, I'm afraid.
