### ISSUE TITLE
Events not picked up within user home directories?

### ISSUE THREAD

**Issue by logiclrd** [martinpitt/fatrace#32]
If I run `fatrace | grep aoeu`, and then I execute this series of commands:
```
echo testing > /root/aoeu
echo testing > /home/logiclrd/aoeu
echo testing > /tmp/aoeu
echo testing > /aoeu
```
...then the output from `fatrace` is:
```
root@visor:/# fatrace | grep aoeu
bash(43160): O /tmp/aoeu
bash(43160): CW /tmp/aoeu
bash(43160): O /aoeu
bash(43160): CW /aoeu
```
What happened to the first two files? Why aren't they shown?

**Comment by logiclrd** [comment]
Hmm, it looks like this distro's standard configuration actually mounts the home directories from different ZFS ... not sure what the terminology is, different ZFS _devices_?
```
rpool/ROOT/ubuntu_znaqup                           116G   704G      107G  /
rpool/USERDATA                                    71.1G   704G       96K  /
rpool/USERDATA/logiclrd_ltzio4                    71.0G   704G     71.0G  /home/logiclrd
rpool/USERDATA/root_ltzio4                        59.9M   704G     59.9M  /root
```
Is this why? But, the `man` page says that without `--current-mount`, "all (real) partitions/mount points are being watched". Or is `rpool/USERDATA/root_ltzio4` not a "real" partition?? But `rpool/ROOT/ubuntu_znaqup` is??

Hmm. 🤔

**Comment by logiclrd** [comment]
Another wrinkle: If I clone this repository and build it, the resulting `fatrace` _does_ show all events. The one bundled with my distro (Ubuntu 22.04) doesn't. What is going on?!

**Comment by logiclrd** [comment]
The `fatrace` from my distro was installed with `apt install fatrace`, which installed package version 0.16.3-1. Not sure where that version number is relevant.

**Comment by logiclrd** [comment]
I've found the source code for 0.16.3-1 and am diffing it with the repo head.

* In `get_fid_event_fd`, the latest version includes additional flags when opening the file: `O_NONBLOCK`, `O_LARGEFILE` and `O_PATH`.
* In `print_event`, the latest version explicitly initializes `proc_fd_stat.st_uid` to `-1`.
* The latest version reads the process name from `/proc/%i/comm` instead of `/proc/%i`.
* The latest version has the option to print the user and group, but it's not enabled by default.
* The latest version explicitly checks for ZFS mount types before ignoring mount points that don't start with '/'.

Maybe it's something to do with that last one??

**Comment by logiclrd** [comment]
Okay, that is in fact what it is. In my comment with the mount points:
```
rpool/ROOT/ubuntu_znaqup                           116G   704G      107G  /
rpool/USERDATA                                    71.1G   704G       96K  /
rpool/USERDATA/logiclrd_ltzio4                    71.0G   704G     71.0G  /home/logiclrd
rpool/USERDATA/root_ltzio4                        59.9M   704G     59.9M  /root
```
...note that the device names in the first columns are not devnodes in `/dev`. They do not start with a forward slash, and the old code assumes that this means they must be virtual things like `procfs` and deliberately does not call `fanotify_mark` for them.

In 407389d7, @achims311 fixed this, but Ubuntu 22.04 had already locked onto a version prior to the fix.

I have verified that this is in fact the cause. If I comment out the `continue;` used to ignore certain mount points (crude, but the smallest possible change for testing), then a build of 0.16.3-1 starts working for files in my home directories.

**Comment by logiclrd** [comment]
One final note, for anybody else running into this issue: It appears that the package for Ubuntu 24.04 `noble` works fine and has no dependency issues. So, from a root shell:
```
apt remove fatrace # If the old jammy package is still installed
wget http://mirrors.kernel.org/ubuntu/pool/universe/f/fatrace/fatrace_0.17.0-1_amd64.deb
dpkg -i fatrace_0.17.0-1_amd64.deb
```
I ran (essentially) these commands on my Ubuntu 22.04 system and the system `fatrace` no longer has this issue. :-)

**Comment by martinpitt** [comment]
Thanks @logiclrd for investigating!
