### ISSUE TITLE
--output FILE not in real time

### ISSUE THREAD

**Issue by setaur** [martinpitt/fatrace#6]
Hey I'm trying to use your tool to backtrack waking up disks in my ZFS pool.
When I run 
```
# cd /mnt/magazyn #zfs mount
# fatrace -c
```
and in another terminal 
```
# ls /mnt/magazyn
```
then immediately I get valid output in first terminal:
```
ls(26115): O /mnt/magazyn
ls(26115): R /mnt/magazyn
ls(26115): RC /mnt/magazyn
```
But when I try to redirect output to file using command
```
# cd /mnt/magazyn; fatrace -c -o /tmp/fatrace_output
```
(or fatrace -c > logfile or fatrace -c | tee logfile)
and in another terminal I start
```
# tail -f /tmp/fatrace_output
```
Accessing /mnt/magazyn, creating, delecting files - logfile stays empty. Only after stopping fatrace with CTRL-C all the missing content appears in the logfile.

It seems that this behavior only happens in case of ZFS mounts. Command started without "-c" saves a lot of logs into logfile in realtime, but I can't find any records from ZFS mounts.

My system: Debian 10 5.9.0-0.bpo.5-amd64
I tried fatrace from Debian Stable repository (0.13-2) and from this github. Result is the same.

**Comment by martinpitt** [comment]
This is actually not specific to ZFS, I get this on ext4 as well. Regular stdout is line buffered, while outputting to a file uses much larger buffers. This is more efficient especially for large amounts of data, but prevents live `tail`ing.

This is easy to fix, commit is coming. Thanks for the report!

**Comment by setaur** [comment]
Thank you for your fast response.
Actually I tested this new version of your program, but I still cannot use it for my purposes without non-trivial hacks.
I have a lot of mounts in my ZFS pool, which I am trying to track down. So I'm trying to create script to watch them all, by running fatrace on each mount and catch collective output - but I cannot. If I use -o FILE option, then I only can use this FILE once for only one mount. Another attempt leads to "Failed to open output file: File exists". I could just run
```
fatrace -c >> output_file & cd another/location; fatrace -c >> output_file
```
but then I don't have line buffering.

Ideally for me there should be extra '--line-buffered' option, just like in case of grep, for all outputs. Or to permit appending to existing file with '-o FILE' option. The latter would also allow for writing into created fifo.

**Comment by martinpitt** [comment]
But now "line buffered" is the default, why would you need an extra option for that?

**Comment by setaur** [comment]
```
fatrace -c >> output_file
```
still doesn't produce realtime output. In commit 06c83e0690ad1e040027715151e24ff9c9c40aa1 you added `setlinebuf (stdout);`, but it's inside `if (option_output)` section, so it's working only with `-o FILE` option. But with that option I can only use one FILE per location. I want to spawn multiple instances of fatrace in multiple locations, all writing to one file. I cannot do this with `-o FILE` option, because it fails if FILE already exists.

After modifying code - moving line 595: `setlinebuf (stdout);` outside braces in example into line 598 - I can get desired program operation. `fatrace -c >> output_file` now is now line-buffered. Now script like this works:
```
#!/bin/bash

fatrace=/path/to/fatrace

finish() {
    [[ "$finished" ]] && exit
    finished=1
    pkill -P $$ fatrace
    rm "$fifo"
    exit
}
trap finish INT TERM EXIT

#fatrace_pids=()
Mountpoints=()
fifo=/tmp/"$(basename "$0").fifo"
mkfifo "$fifo"

while read mountpoint; do
    echo "# $mountpoint" >&2
    cd "$mountpoint" || continue
    Mountpoints+=("$mountpoint")
done < <(mount | grep '^magazyn' | awk '{print $3;}' )

echo '# start' >&2

for mountpoint in "${Mountpoints[@]}"; do
    cd "$mountpoint" || continue
    $fatrace --current-mount >> "$fifo" &
    echo "# fatrace in $mountpoint started" >&2
done 

echo -e '\n'

wait

echo "# finish"
```
All output is concatenated into fifo.

**Comment by martinpitt** [comment]
@setaur: Right, I was misled as this bug report talks about `--output` explicitly. But I see the point, this makes sense with output redirection as well. Done in commit e6e67bb7adfeb4502c791558c3436e22b9ef8d0e
