### ISSUE TITLE
ZFS mounts are not monitored

### ISSUE THREAD

**Issue by carlreinke** [martinpitt/fatrace#7]
`fatrace` doesn't work on ZFS mounts (except `-c` mode) because the `mnt_fsname` is not a device.

A few examples of `mount` output for ZFS filesystems:
```
bpool/BOOT/ubuntu_lkdzni on /boot type zfs (rw,nodev,relatime,xattr,posixacl)
rpool/ROOT/ubuntu_lkdzni on / type zfs (rw,relatime,xattr,posixacl)
rpool/USERDATA/root_lkdzni on /root type zfs (rw,relatime,xattr,posixacl)
```

Having an option to opt-in specified non-device-file-based filesystem types for monitoring would at least make `fatrace` usable with ZFS.  (Just one possible solution.)

**Comment by papamoose** [comment]
I'd also like support for ZFS even if support is minimal. I currently use a really old version [fanotify_watch with a couple lines commented out](https://github.com/papamoose/fanotify_watch/blob/master/fanotify_watch.c#L187-L190) to monitor ZFS mounts for certain files.
