### ISSUE TITLE
"Too many open files"

### ISSUE THREAD

**Issue by melyux** [martinpitt/fatrace#8]
Running fatrace with `--filter=W` results in this error after a few minutes:
```
fatrace: read: Too many open files
```

Looks like this was [reported before](https://bugs.launchpad.net/fatrace/+bug/1858305) on the other repo (what is the relationship of that to this repo?), and it still exists in the latest master of this project. I applied the patch that someone mentioned in the comment on the other issue, and it seems to work so far.

**Comment by martinpitt** [comment]
Thanks! I applied the patch, this makes perfect sense. I'll do a 0.16.3 release now.
