### ISSUE TITLE
Cannot initialize fanotify: Function not implemented

### ISSUE THREAD

**Issue by MySurmise** [martinpitt/fatrace#9]
When I try to start fatrace I always only get `Cannot initialize fanotify: Function not implemented` as a response.

I just installed fatrace with apt, nothing else.

uname -a returns `Linux odroid 5.4.167-240 #1 SMP PREEMPT Sun Feb 13 19:46:51 EST 2022 armv7l armv7l armv7l GNU/Linux`
(It's a ODROID-HC2)

Is that a bug? Is that for me to fix? Is a dependency missing? I have no clue. Keep in mind this is an arm system, maybe that's the problem.

**Comment by MySurmise** [comment]
Oh, I'm using ubuntu 20.04.

**Comment by martinpitt** [comment]
Your kernel does not have [CONFIG_FANOTIFY](https://man7.org/linux/man-pages/man7/fanotify.7.html) enabled. You can try to rebuild it and enable the option, but it's certainly not easy..
